version: '3.1'
services:

  product-service:
    build: .
    container_name: product-service
    image: product-service
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
    expose:
      - "8080"

  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test

volumes:
  pgdata:
